### ISSUE TITLE
Open source this?

### ISSUE THREAD

**Issue by malcolmwhat** [mcgill-robotics/rover_tiva#11]
Since this is deprecated, we should either delete it or open source it (imo).

I'm honestly fine with adjusting the README, deleting non-implemented stuff and open sourcing it, because it *is* a functional implementation of `tiva` <-> `ROS` interaction, which we didn't exactly have in abundance as reference material when doing this project.

It may come in handy or some people may be like "wtf are you doing", either way I don't see us losing anything.

Any comments? @jmacneal @sdahdah @anassinator

**Comment by anassinator** [comment]
done
